In [1]:
import pickle
import pandas as pd
import json
import numpy as np
from methods.load_data import LoadData
from methods.preproc import Preproc
from methods.feature_endineering import FeatureEngineering
from catboost import CatBoostClassifier
import warnings
warnings.filterwarnings("ignore")

In [2]:
 # или CatBoostRegressor
model = CatBoostClassifier()
model.load_model('models/catboost_model.cbm')

CatBoostClassifier(auto_class_weights='Balanced', depth=7, eval_metric='AUC', iterations=2000, l2_leaf_reg=2, learning_rate=0.01, loss_function='Logloss', random_seed=0, use_best_model=True, verbose=50)

In [3]:
features = model.feature_names_
cat_features = []

In [4]:
with open('models/tickers.pkl', 'rb') as f:
    tickers = pickle.load(f)

In [5]:
# Получаем данные за сегодня после закрытия рынка
# start = (datetime.now()).strftime('%Y-%m-%d')
# print(start)
start = '2026-03-07'
load_cls = LoadData()
df, skipped = load_cls.load_moex_universe(tickers, start_date=start)

# Первичный осмотр данных
df.head()

Loading MOEX universe: 100%|██████████| 69/69 [00:41<00:00,  1.67it/s]

        date    open    high     low   close    volume ticker
0 2026-03-09  13.250  13.795  13.240  13.703  62814100   AFKS
1 2026-03-10  13.788  13.869  13.450  13.490  58257200   AFKS
2 2026-03-11  13.564  13.715  13.314  13.413  42627100   AFKS
3 2026-03-12  13.400  13.528  13.271  13.333  52491400   AFKS
4 2026-03-13  13.335  13.499  13.320  13.332  38712000   AFKS

In [6]:
df.shape

(1725, 7)

In [7]:
path = f'models/history_dataset.pickle'

with open(path, 'rb') as f:
    df_h = pickle.load(f)

In [8]:
df = pd.concat([df_h, df])

In [9]:
df

           date      open      high       low     close       volume ticker
2850 2025-10-13    12.400    12.749    12.210    12.373  103647600.0   AFKS
2851 2025-10-14    12.374    12.448    12.130    12.250   40709400.0   AFKS
2852 2025-10-15    12.290    12.440    12.075    12.230   56002600.0   AFKS
2853 2025-10-16    12.230    13.764    12.145    13.538  166151100.0   AFKS
2854 2025-10-17    13.660    13.740    13.167    13.513  115543500.0   AFKS
...         ...       ...       ...       ...       ...          ...    ...
1720 2026-04-06  4142.000  4195.500  4102.500  4182.000    1225240.0   YDEX
1721 2026-04-07  4182.000  4243.000  4161.500  4210.000     668661.0   YDEX
1722 2026-04-08  4232.500  4290.000  4217.500  4238.000     665376.0   YDEX
1723 2026-04-09  4249.000  4261.000  4150.000  4162.000     467387.0   YDEX
1724 2026-04-10  4172.500  4198.000  4144.500  4150.500     366038.0   YDEX

[8597 rows x 7 columns]

In [10]:
preproc_cls = Preproc()
df = preproc_cls.preproc(df, threshold=0.3)

In [11]:
df = df.sort_values(by =['ticker', 'date'])
df = df.groupby(['ticker']).tail(100)

path = f'models/history_dataset.pickle'

with open(path, 'wb') as f:
    pickle.dump(df_h, f)

In [12]:
with open("models/features_intervals.json", "r", encoding="utf-8") as f:
    features_intervals = json.load(f)

feature_cls = FeatureEngineering()
df = feature_cls.feature_eng(df, features_intervals, cat_features)

In [13]:
with open("models/threshold.json", "r", encoding="utf-8") as f:
    threshold = json.load(f)

In [23]:
df['probability'] = model.predict_proba(df[features])[:, 1]  # Predict probabilities for the positive class
df['predict'] = (df['probability'] >= threshold).astype(int) #

In [24]:
df = df.sort_values(by=['ticker', 'date'])
result = df.groupby(['ticker']).tail(1)

In [29]:
result = result[['ticker', 'predict', 'probability']]
result['trend'] = np.where(result['predict']==1, 'UP', 'DOWN')
result['probability'] = np.where(result['predict']==1, result['probability'], 1-result['probability'])
result

     ticker  predict  probability trend
99     AFKS        1     0.519018    UP
199    AFLT        1     0.548701    UP
299    ALRS        0     0.529905  DOWN
399    AQUA        0     0.587122  DOWN
499    ASTR        1     0.608098    UP
...     ...      ...          ...   ...
6496   VKCO        1     0.501185    UP
6596   VSEH        1     0.515175    UP
6696   VTBR        1     0.587557    UP
6796     X5        1     0.587068    UP
6896   YDEX        1     0.498644    UP

[69 rows x 4 columns]

In [30]:
# Устанавливаем ticker как индекс, выбираем нужные колонки и преобразуем
result_dict = result.set_index('ticker')[['trend', 'probability']].to_dict(orient='index')

In [31]:
result_dict

{'AFKS': {'trend': 'UP', 'probability': 0.5190176378291879},
 'AFLT': {'trend': 'UP', 'probability': 0.5487007417433057},
 'ALRS': {'trend': 'DOWN', 'probability': 0.529904955645865},
 'AQUA': {'trend': 'DOWN', 'probability': 0.587122239880722},
 'ASTR': {'trend': 'UP', 'probability': 0.6080975668365253},
 'BELU': {'trend': 'DOWN', 'probability': 0.5636035125114054},
 'BSPB': {'trend': 'UP', 'probability': 0.5873815453829626},
 'CBOM': {'trend': 'DOWN', 'probability': 0.548141148612487},
 'CHMF': {'trend': 'DOWN', 'probability': 0.5361823817538953},
 'CNRU': {'trend': 'UP', 'probability': 0.5288287707683729},
 'DOMRF': {'trend': 'UP', 'probability': 0.6034933171956279},
 'ELFV': {'trend': 'UP', 'probability': 0.5520553630243628},
 'ENPG': {'trend': 'DOWN', 'probability': 0.591720832619805},
 'EUTR': {'trend': 'DOWN', 'probability': 0.6073814525715322},
 'FEES': {'trend': 'UP', 'probability': 0.5528563771790055},
 'FIXR': {'trend': 'DOWN', 'probability': 0.5258734404350995},
 'FLOT': {'trend': 'DOWN', 'probability': 0.5508334692783059},
 'GAZP': {'trend': 'UP', 'probability': 0.5179225065246681},
 'GEMC': {'trend': 'UP', 'probability': 0.5747599503664996},
 'GMKN': {'trend': 'DOWN', 'probability': 0.5262766661416958},
 'HEAD': {'trend': 'UP', 'probability': 0.5246485199635866},
 'HYDR': {'trend': 'UP', 'probability': 0.5016865601711471},
 'IRAO': {'trend': 'UP', 'probability': 0.5806556976937247},
 'LEAS': {'trend': 'DOWN', 'probability': 0.5489886818710266},
 'LENT': {'trend': 'UP', 'probability': 0.5230792267126148},
 'LKOH': {'trend': 'DOWN', 'probability': 0.5165085354989658},
 'LSRG': {'trend': 'UP', 'probability': 0.5052734541524241},
 'MAGN': {'trend': 'DOWN', 'probability': 0.5285965728965343},
 'MBNK': {'trend': 'UP', 'probability': 0.5193407344435429},
 'MDMG': {'trend': 'DOWN', 'probability': 0.5109245422550828},
 'MOEX': {'trend': 'UP', 'probability': 0.5375734463284793},
 'MSNG': {'trend': 'DOWN', 'probability': 0.5632212600605558},
 'MTLR': {'trend': 'UP', 'probability': 0.4979387533826504},
 'MTLRP': {'trend': 'DOWN', 'probability': 0.5245337592054207},
 'MTSS': {'trend': 'UP', 'probability': 0.5442514290094542},
 'MVID': {'trend': 'DOWN', 'probability': 0.5358317083749156},
 'NLMK': {'trend': 'UP', 'probability': 0.49863729393088263},
 'NVTK': {'trend': 'DOWN', 'probability': 0.5549245420856841},
 'OZON': {'trend': 'UP', 'probability': 0.5275152686180323},
 'OZPH': {'trend': 'UP', 'probability': 0.5506532999504251},
 'PHOR': {'trend': 'DOWN', 'probability': 0.5432000843537174},
 'PIKK': {'trend': 'UP', 'probability': 0.5784450010531028},
 'PLZL': {'trend': 'UP', 'probability': 0.5019771243475443},
 'POSI': {'trend': 'DOWN', 'probability': 0.5168651859443898},
 'RAGR': {'trend': 'UP', 'probability': 0.5639443867185933},
 'RENI': {'trend': 'UP', 'probability': 0.5304161435912695},
 'RNFT': {'trend': 'DOWN', 'probability': 0.6090758999540814},
 'ROSN': {'trend': 'DOWN', 'probability': 0.5828387227388855},
 'RTKM': {'trend': 'DOWN', 'probability': 0.5151223393470088},
 'RTKMP': {'trend': 'UP', 'probability': 0.5187466077788468},
 'RUAL': {'trend': 'UP', 'probability': 0.5297705698285486},
 'SBER': {'trend': 'UP', 'probability': 0.5975588058704315},
 'SBERP': {'trend': 'UP', 'probability': 0.588115265537473},
 'SELG': {'trend': 'DOWN', 'probability': 0.6091177494012053},
 'SFIN': {'trend': 'UP', 'probability': 0.4943882761136871},
 'SGZH': {'trend': 'UP', 'probability': 0.5443082111861043},
 'SMLT': {'trend': 'DOWN', 'probability': 0.6520743559951205},
 'SVCB': {'trend': 'DOWN', 'probability': 0.5468228114115878},
 'T': {'trend': 'UP', 'probability': 0.5300414043371053},
 'TATN': {'trend': 'DOWN', 'probability': 0.5421217188412858},
 'TATNP': {'trend': 'DOWN', 'probability': 0.5585139906935137},
 'TGKA': {'trend': 'UP', 'probability': 0.5504041243222082},
 'TRNFP': {'trend': 'UP', 'probability': 0.575594727495016},
 'UPRO': {'trend': 'UP', 'probability': 0.5520158011569573},
 'VKCO': {'trend': 'UP', 'probability': 0.5011853354100384},
 'VSEH': {'trend': 'UP', 'probability': 0.515174785743806},
 'VTBR': {'trend': 'UP', 'probability': 0.5875571860407546},
 'X5': {'trend': 'UP', 'probability': 0.5870684180630181},
 'YDEX': {'trend': 'UP', 'probability': 0.49864401097382693}}

In [33]:
with open("result/signals.json", "w", encoding="utf-8") as f:
    json.dump(result_dict, f, ensure_ascii=False, indent=4)